##
## This file is part of hl://Dig <https://solbu.github.io/hldig/>
##
## Copyright (c) 2017 The hl://Dig Group
## For copyright details, see the file COPYING in your distribution
## or the GNU Library General Public License version 2 or later
## <http://www.gnu.org/copyleft/lgpl.html>

#
# To compile with profiling do the following:
#
# make CFLAGS=-g CXXFLAGS=-g PROFILING=-p all
#

AUTOMAKE_OPTIONS = foreign no-dependencies

PACKAGE = @PACKAGE@
VERSION = @VERSION@

AM_CPPFLAGS=	\
		-DDEFAULT_CONFIG_FILE=\"$(DEFAULT_CONFIG_FILE)\" \
		-I$(top_srcdir)/include -I$(top_srcdir)/hllib \
		-I$(top_srcdir)/htnet -I$(top_srcdir)/htcommon \
		-I$(top_srcdir)/hlword \
		-I$(top_srcdir)/db -I$(top_builddir)/db \
		$(LOCAL_DEFINES) $(PROFILING) \
		-DLOCALEDIR=\"$(localedir)\"

HLLIBS=		$(top_builddir)/htnet/libhtnet.la \
		$(top_builddir)/htcommon/libcommon.la \
		$(top_builddir)/hlword/libhlword.la \
		$(top_builddir)/hllib/libhl.la \
		$(top_builddir)/db/libhldb.la

localedir = @localedir@
LIBS = @LIBINTL@ @LIBS@

LDADD = $(HLLIBS) @LIBINTL@
