# Generated automatically from Makefile.config.in by configure.
##
## Makefile.config
##
## This file is part of HTDig
##
include /home/turtle/src/ht/CONFIG

#
# You should not have to modify anything below this point.
#
DEFINES=	-DDEFAULT_CONFIG_FILE=\"$(DEFAULT_CONFIG_FILE)\"
SHELL=		/bin/sh
CXX=		c++
CC=		gcc
RANLIB=		ranlib
MAKEDEPEND=	/home/turtle/src/ht/makedp
RM=		rm -f
AR=		/usr/ccs/bin/ar
SED=		/opt/bin/sed
INSTALL=	/home/turtle/src/ht/install-sh -c
TAR=		tar

CCC=		$(CXX)
LIBDIRS=	-L../htlib -L../htcommon -L../gdbm-1.7.3 -L../rx-1.5/rx
INCS=		-I../htlib -I../htcommon -I../include -I../rx-1.5/rx
LIBS=		-lcommon -lht -lgdbm -lrx  -lsocket -lnsl

DIST=		htdig-3.0.7
DISTDIR=	/home/turtle/src/ht/../$(DIST)

CPPFLAGS=	$(CC_OPTIONS) -g -O -DHAVE_CONFIG_H $(INCS)
CXXFLAGS=	-g -O $(LOCAL_DEFINES) $(DEFINES) $(INCS)
LDFLAGS=	$(LIBDIRS)

.SUFFIXES: .cc
.cc.o:
	$(CXX) -c $(CXXFLAGS) $<

.c.o:
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $<

