##
## Makefile.config
##
## This file is part of ht://Dig
##
INCLUDES=	-Wall \
		-DDEFAULT_CONFIG_FILE=\"$(DEFAULT_CONFIG_FILE)\" \
		-I$(top_srcdir)/include -I$(top_srcdir)/htlib \
		-I$(top_srcdir)/htnet -I$(top_srcdir)/htcommon \
		-I$(top_srcdir)/db/dist -I$(top_builddir)/db/dist \
		$(LOCAL_DEFINES)

HTLIBS=		$(top_builddir)/htcommon/libcommon.la \
		$(top_builddir)/htlib/libht.la \
		$(top_builddir)/htnet/libhtnet.la \
		$(top_builddir)/db/dist/libdb.a
