.TH htdig 1 "January 2004"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
htstat \-  returns statistics on the document and word databases, much like the -s option to htdig or htmerge.
.SH SYNOPSIS
.B htstat
.I "[-v][-a][-c configfile][-u]"
.SH "DESCRIPTION"
Htdig retrieves HTML documents using the HTTP protocol and
gathers information from these documents which can later be
used to search these documents. This program can be referred to
as the search robot. 
.SH OPTIONS
.TP
.B \-a
Use alternate work files. Tells htstat to append
.I .work
to database files, causing a second copy of the database to be
built. This allows the original files to be used by htsearch
during the run. 
.TP
.B \-c \fIconfigfile\fR
Use the specified
.I configfile
instead of the default. 
.TP
.B \-u
Give a list of URLs in the document database.
.TP
.B \-v
Verbose mode. This increases the verbosity of the program.
Using more than 2 is probably only useful for debugging
purposes. The default verbose mode (using only one \fI\-v\fR) gives
a nice progress report while digging. 
.SH "FILES"
.TP
.B /etc/htdig/htdig.conf
The default configuration file.
.SH "SEE ALSO"
Please refer to the HTML pages (in the htdig-doc package)
.B /usr/share/doc/htdig-doc/html/index.html
and the manual pages
.I htdigconfig(8)
,
.I htdig(1)
and
.I htmerge(1)
for a detailed description of ht://Dig and its commands.

.SH AUTHOR
This manual page was written by Robert Ribnitz, 
based on the HTML documentation of ht://Dig.
