HTDIG_SHARED_LIBADD = -R/usr/local/lib -L/usr/local/lib -lbz2
prefix = /nfs/local/linux
exec_prefix = $(prefix)
libdir = ${exec_prefix}/lib
prefix = /nfs/local/linux
phplibdir = modules
#phplibdir = $(PWD)/modules
PHP_COMPILE = $(LIBTOOL) --mode=compile $(COMPILE) -c $<
CC = gcc
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = -DHAVE_CONFIG_H
CXX =
DEFS =
EXTENSION_DIR = /usr/local/lib/php/extensions/no-debug-non-zts-20010901
EXTRA_LDFLAGS =
EXTRA_LIBS =
INCLUDES = -I/nfs/local/linux/include/php4 -I/nfs/local/linux/include/php4/main -I/nfs/local/linux/include/php4/Zend -I/nfs/local/linux/include/php4/TSRM -I/usr/local/include
LEX =
LEX_OUTPUT_ROOT =
LFLAGS =
SHARED_LIBTOOL = $(LIBTOOL)
LIBTOOL = $(SHELL) $(top_builddir)/libtool
SHELL = /bin/sh
