top_srcdir   = /nfs/users/rnw/nealr/code/htdig/htdig-CVS-linux/libhtdigphp
top_builddir = /nfs/users/rnw/nealr/code/htdig/htdig-CVS-linux/libhtdigphp
srcdir       = /nfs/users/rnw/nealr/code/htdig/htdig-CVS-linux/libhtdigphp/
builddir     = /nfs/users/rnw/nealr/code/htdig/htdig-CVS-linux/libhtdigphp/
VPATH        = /nfs/users/rnw/nealr/code/htdig/htdig-CVS-linux/libhtdigphp/
# $Id: Makefile,v 1.1 2004/03/20 01:31:21 nealr Exp $

LTLIBRARY_NAME        = libhtdigphp.la
LTLIBRARY_SOURCES     = htdigphp.c
LTLIBRARY_SHARED_NAME = libhtdigphp.la
LTLIBRARY_SHARED_LIBADD = -lhtdig

include $(top_srcdir)/build/dynlib.mk

DEFS += -I../libhtdig 
